# Generated by Django 6.0 on 2025-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
