# Generated by Django 6.0 on 2025-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0003_fill_company_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
