# Generated by Django 6.0 on 2025-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0005_fill_event_company_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company',
        ),
        migrations.AlterField(
            model_name='event',
            name='company_uuid',
            field=models.UUIDField(),
        ),
    ]
