# Generated by Django 6.0 on 2025-12-29 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0006_remove_event_company_alter_event_company_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
