# Generated by Django 6.0 on 2025-12-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0007_remove_company_company_id_alter_company_company_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_uuid',
            new_name='company_id',
        ),
    ]
