# Generated by Django 6.0 on 2025-12-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_pk_uuid', '0008_rename_company_uuid_company_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company_uuid',
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ams_pk_uuid.company'),
        ),
    ]
